### ISSUE TITLE
Not a properly formatted package

### ISSUE THREAD

**Issue by AdamBuczynski** [unspace/un-calendar#10]
Getting the following notice on ember-cli version 0.2.5:
```
The package `un-calendar` is not a properly formatted package, we have used a fallback 
lookup to resolve it at `..../node_modules/un-calendar`. This is generally caused by an 
addon not having a `main` entry point (or `index.js`).
```

**Comment by AdamBuczynski** [comment]
Seems the fix is to change:
```
"main": "dist/cjs/main.js",
```
to:
```
"main": "dist/cjs/un-calendar.js",
```
in package.json

**Comment by heycarsten** [comment]
Woomp, thanks for the find @AdamBuczynski!

**Comment by heycarsten** [comment]
This should be fixed now. Ref ab60bd21

**Comment by AdamBuczynski** [comment]
Cheers @heycarsten, any idea how long it usually would take until 0.2.3 is available in npm?

**Comment by heycarsten** [comment]
@ghedamat can you publish it to NPM when you have a moment, I'm not a collaborator on the package.

**Comment by ghedamat** [comment]
@AdamBuczynski @heycarsten done

also @heycarsten added you as a collaborator, but npm site is a bit borken, so maybe give it a shot and let me know if it works

thanks!
