### ISSUE TITLE
Update example to use new project name

### ISSUE THREAD

**Issue by hagenburger** [unspace/un-calendar#6]
The example still refers to `ui-calendar`:

http://emberjs.jsbin.com/komop/2/

**Comment by ghedamat** [comment]
@hagenburger @shivanibhanwal as said in other issues, sorry :/ we missed a bunch of comments and we definitely neglected this project more than we would have liked to.

hopefully we'll have some time soon to do an overall update and port it to latest ember, update docs etc.
